// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;
using PropertyChanged;

namespace FanArtPortable.Tv
{
    public class TvItem : BaseItem
    {
    }

    public class Seasonthumb : BaseItem
    {
        [JsonProperty("season")]
        public string Season { get; set; }
    }

    [ImplementPropertyChanged]
    public class TvResponse
    {
        [JsonProperty("series")]
        public string Series { get; set; }

        [JsonProperty("clearlogos")]
        public TvItem[] TvItems { get; set; }

        [JsonProperty("cleararts")]
        public TvItem[] Cleararts { get; set; }

        [JsonProperty("tvthumbs")]
        public TvItem[] Tvthumbs { get; set; }

        [JsonProperty("seasonthumbs")]
        public Seasonthumb[] Seasonthumbs { get; set; }
    }
}
